name: Build

on:
  merge_group:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  build:
    runs-on: windows-2022

    env:
      Solution_Path: Sample\Auth0MauiApp.sln

    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          solution-path: Sample\Auth0MauiApp.sln
