name: Build

on:
  push:
    branches: [ main, frederikprijck-patch-1 ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:
    
jobs:
  build:
    runs-on: windows-2022

    env:
      Solution_Path: Sample\Auth0MauiApp.sln
    
    steps:
      - uses: actions/checkout@v4
          
      - name: Install .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.402'
      - name: Build
        run: dotnet restore $env:Solution_Path --configuration Release
      
