name: Build and Test

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Package
    runs-on: windows-2022

    env:
      Solution_Path: Sample\Auth0MauiApp.sln

    steps:
      - uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8"

      - name: Install .NET Workloads
        run: dotnet workload install maui

      - name: Build
        run: dotnet build $env:Solution_Path --configuration Release
